# Generated by Django 4.0.2 on 2022-03-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweatygames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=30)),
            ],
        ),
    ]
